version: '2'
services:
  trezor-user-env-unix:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  suite-dev:
    extends:
      file: docker-compose.suite-dev.yml
      service: suite-dev
    network_mode: service:trezor-user-env-unix

  test-open:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    build:
      context: .
      dockerfile: ./test-runner/Dockerfile
    container_name: test-runner
    ipc: host
    depends_on:
      - suite-dev
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
    environment:
      - CYPRESS_SNAPSHOT=$CYPRESS_SNAPSHOT
      - CYPRESS_updateSnapshots=$CYPRESS_updateSnapshots
      - CYPRESS_baseUrl=http://localhost:8000
      - CYPRESS_defaultCommandTimeout=60000  # on dev server, due to on-demand compilation nature of next.js, we need much longer timeout
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    working_dir: /e2e
    command: bash -c "cypress open --project /e2e/packages/integration-tests/projects/suite-web"
    # if you want to debug run_tests.js (which runs tests in CI) locally
    # command: bash -c "node ./packages/integration-tests/projects/suite-web/run_tests.js"
    volumes:
      - ../:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
  bitcoin-regtest:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env-regtest  # this is a special image that runs regtest and blockbook
    network_mode: service:trezor-user-env-unix
