version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  connect-explorer-dev:
    container_name: connect-explorer-dev
    extends:
      service: suite-base
      file: docker-compose.suite-base.yml
    command: bash -c "yarn workspace @trezor/connect-explorer dev"
    network_mode: service:trezor-user-env-unix

  test-run:
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    container_name: explorer-test-runner
    depends_on:
      - trezor-user-env-unix
      - connect-explorer-dev
    network_mode: service:trezor-user-env-unix
    environment:
      - URL=$URL
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - DISPLAY=$DISPLAY
      - HEADLESS=false
      # useful for debugging tests
      - PWDEBUG=console
      - TEST_FILE=$TEST_FILE
      - IS_WEBEXTENSION=$IS_WEBEXTENSION
    working_dir: /trezor-suite
    command: bash -c "docker/wait-for-200.sh http://localhost:8088/index.html && yarn workspace @trezor/connect-popup test:e2e $TEST_FILE"
    volumes:
      - ../:/trezor-suite
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
