version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  test-run:
    image: mcr.microsoft.com/playwright:focal
    container_name: webextension-test-runner
    ipc: host
    depends_on:
      - trezor-user-env-unix
    network_mode: service:trezor-user-env-unix
    environment:
      - URL=$URL
      - HEADLESS=$HEADLESS
      - DISPLAY=$DISPLAY
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - CI_JOB_URL=$CI_JOB_URL
      - CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
      - CI_JOB_NAME=$CI_JOB_NAME
        # useful for debugging tests
      - PWDEBUG=console

    working_dir: /trezor-suite
    command: bash -c "npx playwright install && yarn workspace @trezor/connect-webextension test:e2e"
    volumes:
      - ../:/trezor-suite
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
