version: "3"
services:
  trezor-user-env-unix:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: bridge  # this makes docker reuse existing networks
  test-run:
    image: $CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX/cypress/included:8.3.0
    entrypoint: []
    environment:
      - CYPRESS_SNAPSHOT=$CYPRESS_SNAPSHOT
      - CYPRESS_updateSnapshots=$CYPRESS_updateSnapshots
      - CYPRESS_baseUrl=$CYPRESS_baseUrl
      - CYPRESS_ASSET_PREFIX=$CYPRESS_ASSET_PREFIX
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - TEST_GROUP=$TEST_GROUP
      - TRACK_SUITE_URL=$TRACK_SUITE_URL
      - ALLOW_RETRY=$ALLOW_RETRY
      - CI_JOB_URL=$CI_JOB_URL
      - CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
      - CI_COMMIT_MESSAGE=$CI_COMMIT_MESSAGE
      - CI_COMMIT_SHA=$CI_COMMIT_SHA
      - CI_RUNNER_DESCRIPTION=$CI_RUNNER_DESCRIPTION
      - FIRMWARE=$FIRMWARE
    network_mode: service:trezor-user-env-unix
    working_dir: /trezor-suite
    command: bash -c "node ./packages/integration-tests/projects/suite-web/run_tests.js --project /trezor-suite/packages/integration-tests/projects/suite-web --stage=$TEST_GROUP"
    volumes:
      - ../:/trezor-suite
  bitcoin-regtest:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env-regtest  # this is a special image that runs regtest and blockbook
    network_mode: service:trezor-user-env-unix
