sudo: required
language: node_js
dist: trusty

node_js:
  - "12"

before_script:
  - yarn

env:
  - GOAL=flow
  - GOAL=eslint
  - GOAL=build

script: make $GOAL

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
