name: "[Bot] rebase pull request"

on:
  issue_comment:
    types: [created]

jobs:
  rebase-pr:
    name: Rebase pull request
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - name: Respond in pull request
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Start rebasing: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            })
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TREZOR_BOT_TOKEN }}
      - name: Auto rebase pull request
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: true
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
      - name: Report failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Rebasing failed, please rebase manually."
            })
