name: "[Bot] add to GitHub Project"

on: [issues, pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  add-to-project-suite-pull-requests:
    name: Add new pull request to the Pull Requests project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@c7ca843e950d8c8f1917b6aac913b15939da322a
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/trezor/projects/62
          github-token: ${{ secrets.TREZOR_BOT_TOKEN }}
