name: "[Check] @trezor/connect version check"

on:
  pull_request:
    branches:
      - release/connect-v9

jobs:
  version-beta-check:
    name: Check if connect version is beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash ./ci/scripts/check-beta-version.sh
        continue-on-error: true

  version-bump-check:
    name: Check connect version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: |
          yarn install
          node ci/scripts/check-version.js connect npm-release latest
        continue-on-error: true

  dependencies-check:
    name: Check connect dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: "check npm dependencies"
        continue-on-error: true
        run: |
          yarn install
          node ci/scripts/check-npm-dependencies connect
          node ci/scripts/check-npm-dependencies connect-web
