suite codesign deploy staging-suite:
  stage: deploy to staging
  needs:
    - suite-web build stable codesign
    - suite-desktop build mac codesign
    - suite-desktop build linux codesign
    - suite-desktop build windows codesign
    - suite-web-landing build stable
  environment:
    name: ${CI_BUILD_REF_NAME}-staging-suite
    url: ${STAGING_SUITE_SERVER_URL}
  before_script: []
  only:
    refs:
      - codesign
  when: manual
  script:
    - source ${STAGING_SUITE_DEPLOY_KEYFILE}
    - mkdir -p packages/suite-web/build/static/desktop
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.AppImage ./packages/suite-web/build/static/desktop || :'
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.AppImage.asc ./packages/suite-web/build/static/desktop || :'
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.dmg ./packages/suite-web/build/static/desktop || :'
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.dmg.asc ./packages/suite-web/build/static/desktop || :'
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.exe ./packages/suite-web/build/static/desktop || :'
    - 'rsync --delete -va "${DESKTOP_APP_NAME}"-*.exe.asc ./packages/suite-web/build/static/desktop || :'
    - cd packages/suite-web
    - ./scripts/s3sync.sh staging-suite
    - cd -
    - cd packages/suite-web-landing
    - ./scripts/s3sync.sh staging-suite
  tags:
    - deploy

suite-desktop github release:
  stage: deploy to production
  needs:
    - suite-desktop build mac codesign
    - suite-desktop build linux codesign
    - suite-desktop build windows codesign
  environment:
    name: ${CI_BUILD_REF_NAME}-staging-suite
    url: ${STAGING_SUITE_SERVER_URL}
  before_script: []
  only:
    refs:
      - codesign
  when: manual
  script:
    - gh config set prompt disabled
    - VERSION=$(jq -r .suiteVersion packages/suite/package.json)
    - gh release create --repo trezor/trezor-suite --draft v${VERSION}  --title "v${VERSION}" ./Trezor-Suite* latest*
  tags:
    - deploy
