name: "[Release] connect v9 staging"

permissions:
  id-token: write # for fetching the OIDC token
  contents: read # for actions/checkout

on:
  workflow_dispatch:

jobs:
  # Version should have been bumped by now thanks to ./ci/scripts/connect-release-init-npm.js
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Extract connect version
        id: set-version
        run: echo "version=$(node ./ci/scripts/get-connect-version.js)" >> $GITHUB_OUTPUT

  check-version-match:
    runs-on: ubuntu-latest
    needs: [extract-version]
    steps:
      - uses: actions/checkout@v4

      - name: Check connect version match
        uses: ./.github/actions/check-connect-version-match
        with:
          branch_ref: "${{ github.ref }}"
          extracted_version: "${{ needs.extract-version.outputs.version }}"

  # This job deploys to staging-connect.trezor.io/9.x.x
  deploy-staging-semantic-version:
    needs: [extract-version, check-version-match]
    environment: staging-connect
    name: "Deploying to staging-connect.trezor.io/${{ needs.extract-version.outputs.version }}"
    runs-on: ubuntu-latest
    # Branch should have been created by workflow .github/workflows/release-connect-v9-init.yml
    if: startsWith(github.ref, 'refs/heads/release/connect/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/connect/${{  needs.extract-version.outputs.version }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Build and deploy to staging-connect.trezor.io/9.x.x
        uses: ./.github/actions/release-connect
        with:
          awsRoleToAssume: "arn:aws:iam::538326561891:role/gh_actions_connect_staging_deploy"
          awsRegion: "eu-central-1"
          serverHostname: "staging-connect.trezor.io"
          serverPath: ${{ needs.extract-version.outputs.version }}
          buildArtifacts: "true"
          uploadArtifacts: "true"

  # This job deploys to staging-connect.trezor.io/9
  deploy-staging-v9:
    needs: [extract-version, check-version-match]
    environment: staging-connect
    name: "Deploying to staging-connect.trezor.io/9"
    runs-on: ubuntu-latest
    # Branch should have been created by workflow .github/workflows/release-connect-v9-init.yml
    if: startsWith(github.ref, 'refs/heads/release/connect/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/connect/${{  needs.extract-version.outputs.version }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Build and deploy to staging-connect.trezor.io/9
        uses: ./.github/actions/release-connect
        with:
          awsRoleToAssume: "arn:aws:iam::538326561891:role/gh_actions_connect_staging_deploy"
          awsRegion: "eu-central-1"
          serverHostname: "staging-connect.trezor.io"
          serverPath: "9"
          buildArtifacts: "true"
          uploadArtifacts: "true"
