# TODOs:
# - add release_to_npm section (now in gitlab). should be triggered after release_trezor-io is done
# - read new version from yarn workspace @trezor/connect version:<semver> and use it in commit messages etc
# - consider generation of changelog etc
# - in release/connect-v9 branch PR, post info about changed files only for connect?

name: "[Release] @trezor/connect v9 bump version"

on:
  workflow_dispatch:
    inputs:
      semver:
        required: true
        type: choice
        description: Version type
        options:
          - beta
          - patch
          - minor

jobs:
  bump-version-pr:
    name: Bump connect version & create PR to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Run @trezor/connect create release branch
        run: |
          if [ '${{ github.event.inputs.semver }}' == 'beta' ]
          then
              git checkout -B beta-release/connect
          else
              git checkout -B npm-release/connect
          fi
          npm install -g yarn && yarn install
          git config --global user.name "trezor-ci"
          git config --global user.email "${{ secrets.TREZOR_BOT_EMAIL }}"
          yarn workspace @trezor/connect version:${{ github.event.inputs.semver }}
          yarn install --no-immutable
          git add . && git commit -m "release: @trezor/connect (${{ github.event.inputs.semver }})" && git push origin npm-release/connect -f
          gh config set prompt disabled
          gh pr create --repo trezor/trezor-suite --title "npm-release @trezor/connect ${{ github.event.inputs.semver }} [1/2]" --body-file "docs/releases/connect-npm.md" --base develop
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
