name: "[Release] connect bump versions"

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: semver
        options:
          - patch
          - minor
          - prerelease

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TREZOR_BOT_TOKEN }}
          # Fetch all commit history because Script connect-bump-versions.ts needs them to produce CHANGELOG for packages.
          fetch-depth: 0
          # `ref` makes sure that we checkout the branch we are running workflow on.
          ref: ${{ github.head_ref }}
          # `submodules` are required to run `yarn build:libs`.
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      # The script connect-bump-versions.ts needs to build packages so dependencies are required.
      - name: Build dependencies
        run: yarn build:libs

      - name: Setup Git config
        run: |
          git config --global user.name "trezor-ci"
          git config --global user.email "${{ secrets.TREZOR_BOT_EMAIL }}"

      - name: Check dependencies to update
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        run: |
          yarn tsx ./ci/scripts/connect-bump-versions.ts ${{ github.event.inputs.semver }}
