#name: "[Check]: Shell validation"
#
#on:
#  pull_request:
#    paths:
#      - "**.sh"
#jobs:
#  shellcheck:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: shellcheck
#        run: ./scripts/shellcheck.sh
