name: "[Test] @trezor/blockchain-link"

on:
  push:
    branches:
      - develop
    paths:
      - "packages/blockchain-link"
      # dependencies of packages/blockchain-link
      - "packages/utxo-lib"
      - "packages/utils"
  pull_request:
    paths:
      - "packages/blockchain-link"
      # dependencies of packages/blockchain-link
      - "packages/utxo-lib"
      - "packages/utils"
  workflow_dispatch:

jobs:
  test-blockchain-link:
    name: Test @trezor/blockchain-link
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
            # todo: not sure if we wan't to test other versions of node?
            # 14.x,
            16.x,
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"
      - run: node --version
      - run: yarn
      - run: yarn build:libs
      - run: git status
      - run: yarn workspace @trezor/blockchain-link build:workers
      - run: "./docker/docker-blockchain-link-test.sh"
